# Generated by Django 5.2.1 on 2025-05-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du capteur')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('device_type', models.CharField(choices=[('HEART_RATE', 'Capteur de fréquence cardiaque'), ('BLOOD_PRESSURE', 'Capteur de tension artérielle'), ('TEMPERATURE', 'Capteur de température corporelle'), ('OXYGEN', "Capteur d'oxygène sanguin")], max_length=100, verbose_name='Type de capteur')),
                ('topic', models.CharField(max_length=255, unique=True, verbose_name='Adresse MQTT')),
                ('auth_token', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name="Token d'authentification MQTT")),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Capteur actif')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
