# Generated by Django 5.2.1 on 2025-06-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='auth_token',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True, verbose_name="Token d'authentification MQTT"),
        ),
    ]
