# Generated by Django 5.2.1 on 2025-05-31 19:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Elevée'), ('CRITICAL', 'Critique')], default='LOW', max_length=20, verbose_name='Niveau de gravité')),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(5)], verbose_name="Message d'alerte")),
                ('status', models.CharField(choices=[('NEW', 'Nouvelle'), ('RESOLVED', 'Resolue')], default='NEW', max_length=20, verbose_name='Statut')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date de mesure')),
                ('resolve_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='devices.device')),
                ('telemetry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='telemetry.telemetry')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
