# Generated by Django 5.2.1 on 2025-05-31 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NORMAL', 'Normale'), ('WARNING', 'Avertissement'), ('CRITICAL', 'Critique')], default='NORMAL', max_length=20)),
                ('data_type', models.CharField(choices=[('HEART_RATE', 'Fréquence cardiaque'), ('BLOOD_PRESSURE', 'Tension artérielle'), ('TEMPERATURE', 'Température corporelle'), ('OXYGEN', 'Oxygène sanguin')], max_length=100, verbose_name='Type de données')),
                ('value', models.FloatField(verbose_name='Valeur')),
                ('value2', models.FloatField(blank=True, null=True, verbose_name='Valeur secondaire')),
                ('unite', models.CharField(max_length=10, verbose_name='Unité de mesure')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date de mesure')),
                ('received_at', models.DateTimeField(auto_now=True, verbose_name='Date de réception')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_data', to='devices.device')),
            ],
            options={
                'ordering': ['-timestamp'],
                'constraints': [models.CheckConstraint(condition=models.Q(('timestamp__lte', models.F('received_at'))), name='timestamp_before_received_at')],
            },
        ),
    ]
